meim/run/core/__init__.py
#!/usr/bin/env python3
import os
from flask import Flask
# from flask_login import login_required, current_user, login_manager, user_loader
# import flask_login
from flask_bootstrap import Bootstrap
from core.controllers.cleanlist import melisty
from core.controllers.all_listed import all_listedmez

from core.controllers.general import controller as general
from core.controllers.login import controller as login

omnibus=Flask(__name__)

# login_manager=flask_login.LoginManager()
# login_manager.init_app(omnibus)

Bootstrap(omnibus)

omnibus.register_blueprint(general)
omnibus.register_blueprint(login)
# from core.controllers.bicycle import controller as bicycle

# omnibus.register_blueprint(bicycle)

## first part of modularization
def keymaker(omnibus, filename='secret_key'):
        pathname= os.path.join(omnibus.instance_path, filename)
        print ("pathy: ", pathname, omnibus,  omnibus.instance_path)
        try:
                omnibus.config['SECRET_KEY'] = open(pathname, 'rb').read()

        except IOError:
                parent_directory= os.path.dirname(pathname)
                if not os.path.isdir(parent_directory):
                        os.system('mkdir -p {0}'.format(parent_directory))
                os.system('head -c 24 /dev/urandom > {0}'.format(pathname))
                omnibus.config['SECRET_KEY'] = open(pathname, 'rb').read()


# from core.controllers.hihimez import hihimez
# omnibus.register_blueprint(hihimez)

def blueimportreg(filelist):
    for filename in filelist:
        strex="from core.controllers.{zz}mez import {zz}mez".format(zz=filename)
        strey="omnibus.register_blueprint({zz}mez)".format(zz=filename)
        exec(strex)
        exec(strey)

# blueimportreg(['hihi','meao', 'return'])
blueimportreg(melisty)
omnibus.register_blueprint(all_listedmez)

keymaker(omnibus)

#####
# class User(flask_login.UserMixin):
#     def __init__(self):
#         flask_login.UserMixin.__init__(self)
#
#
#
# login_manager.login_view= "login"
#
# @login_manager.user_loader
# def load_user(user_id):
#     bluepoo = flask_global.current_app.blueprints[request.blueprint]
#
#     if hasattr(blueprint, load_user):
#         return blueprint.load_user(user_id)
#
#
#
#     return User.get(user_id)
    # core.controller.checkidno

meim/run/core/controllers/Flaskmez.py
#!/usr/bin/env python3
from flask import Blueprint, render_template
Flaskmez = Blueprint('Flaskmez', __name__, url_prefix='/Flask')
@Flaskmez.route('/', methods=['GET'])
def show_Flask():
	return render_template('Flaskmez.html')

meim/run/core/controllers/REQUESTSmez.py
#!/usr/bin/env python3
from flask import Blueprint, render_template
REQUESTSmez = Blueprint('REQUESTSmez', __name__, url_prefix='/REQUESTS')
@REQUESTSmez.route('/', methods=['GET'])
def show_REQUESTS():
	return render_template('REQUESTSmez.html')

meim/run/core/controllers/__init__mez.py
#!/usr/bin/env python3
from flask import Blueprint, render_template
__init__mez = Blueprint('__init__mez', __name__, url_prefix='/__init__')
@__init__mez.route('/', methods=['GET'])
def show___init__():
	return render_template('__init__mez.html')

meim/run/core/controllers/ad_hocmez.py
#!/usr/bin/env python3
from flask import Blueprint, render_template
ad_hocmez = Blueprint('ad_hocmez', __name__, url_prefix='/ad hoc')
@ad_hocmez.route('/', methods=['GET'])
def show_ad_hoc():
	return render_template('ad_hocmez.html')

meim/run/core/controllers/all_listed.py
#!/usr/bin/env python3
from flask import Blueprint, render_template, redirect, url_for
all_listedmez = Blueprint('all_listedmez', __name__, url_prefix='/all_listed')
@all_listedmez.route('/', methods=['GET'])
def show_all_listed():
	return render_template('all_listed.html')

meim/run/core/controllers/andmez.py
#!/usr/bin/env python3
from flask import Blueprint, render_template
andmez = Blueprint('andmez', __name__, url_prefix='/and')
@andmez.route('/', methods=['GET'])
def show_and():
	return render_template('andmez.html')

meim/run/core/controllers/asmez.py
#!/usr/bin/env python3
from flask import Blueprint, render_template
asmez = Blueprint('asmez', __name__, url_prefix='/as')
@asmez.route('/', methods=['GET'])
def show_as():
	return render_template('asmez.html')

meim/run/core/controllers/assertmez.py
#!/usr/bin/env python3
from flask import Blueprint, render_template
assertmez = Blueprint('assertmez', __name__, url_prefix='/assert')
@assertmez.route('/', methods=['GET'])
def show_assert():
	return render_template('assertmez.html')

meim/run/core/controllers/bicycle.py
#!/usr/bin/env python3

from flask import Blueprint, render_template

controller = Blueprint('bicycle', __name__, url_prefix='/bicycle')

@controller.route('/', methods=['GET'])
def show_bicycle():
        return render_template('bicycle.html')

meim/run/core/controllers/breakmez.py
#!/usr/bin/env python3
from flask import Blueprint, render_template
breakmez = Blueprint('breakmez', __name__, url_prefix='/break')
@breakmez.route('/', methods=['GET'])
def show_break():
	return render_template('breakmez.html')

meim/run/core/controllers/classmez.py
#!/usr/bin/env python3
from flask import Blueprint, render_template
classmez = Blueprint('classmez', __name__, url_prefix='/class')
@classmez.route('/', methods=['GET'])
def show_class():
	return render_template('classmez.html')

meim/run/core/controllers/cleanlist.py
#!/usr/bin/env python3
melisty=['s_g_s', 'delete', 'not', 'meow', 'requests', 'or', 'header', 'in', 'strings', 'raise', 'REQUESTS', 'if_sdfsdf', 'while', 'print', 'except', 'fa', 'lambda', 'not_header', 'meme_ss', 'finally', 'else_statement', 'ad_hoc', 'list', 'class', 'del_fdsdfdsf', 'pass', 'return_o', '__init__', 'break', 'from', 'is', 'sdfsdf_', 'exec', 'as', 'try', 'return', 'continue', 'and', 'flask_login', 'elif_ssss', 'with', 'global', 'import', 'request', 'yield', 'Flask', 'assert', 'for', 'def']

meim/run/core/controllers/continuemez.py
#!/usr/bin/env python3
from flask import Blueprint, render_template
continuemez = Blueprint('continuemez', __name__, url_prefix='/continue')
@continuemez.route('/', methods=['GET'])
def show_continue():
	return render_template('continuemez.html')

meim/run/core/controllers/defmez.py
#!/usr/bin/env python3
from flask import Blueprint, render_template
defmez = Blueprint('defmez', __name__, url_prefix='/def')
@defmez.route('/', methods=['GET'])
def show_def():
	return render_template('defmez.html')

meim/run/core/controllers/del_fdsdfdsfmez.py
#!/usr/bin/env python3
from flask import Blueprint, render_template
del_fdsdfdsfmez = Blueprint('del_fdsdfdsfmez', __name__, url_prefix='/del fdsdfdsf')
@del_fdsdfdsfmez.route('/', methods=['GET'])
def show_del_fdsdfdsf():
	return render_template('del_fdsdfdsfmez.html')

meim/run/core/controllers/deletemez.py
#!/usr/bin/env python3
from flask import Blueprint, render_template
deletemez = Blueprint('deletemez', __name__, url_prefix='/delete')
@deletemez.route('/', methods=['GET'])
def show_delete():
	return render_template('deletemez.html')

meim/run/core/controllers/elif_ssssmez.py
#!/usr/bin/env python3
from flask import Blueprint, render_template
elif_ssssmez = Blueprint('elif_ssssmez', __name__, url_prefix='/elif ssss')
@elif_ssssmez.route('/', methods=['GET'])
def show_elif_ssss():
	return render_template('elif_ssssmez.html')

meim/run/core/controllers/else_statementmez.py
#!/usr/bin/env python3
from flask import Blueprint, render_template
else_statementmez = Blueprint('else_statementmez', __name__, url_prefix='/else statement')
@else_statementmez.route('/', methods=['GET'])
def show_else_statement():
	return render_template('else_statementmez.html')

meim/run/core/controllers/exceptmez.py
#!/usr/bin/env python3
from flask import Blueprint, render_template
exceptmez = Blueprint('exceptmez', __name__, url_prefix='/except')
@exceptmez.route('/', methods=['GET'])
def show_except():
	return render_template('exceptmez.html')

meim/run/core/controllers/execmez.py
#!/usr/bin/env python3
from flask import Blueprint, render_template
execmez = Blueprint('execmez', __name__, url_prefix='/exec')
@execmez.route('/', methods=['GET'])
def show_exec():
	return render_template('execmez.html')

meim/run/core/controllers/famez.py
#!/usr/bin/env python3
from flask import Blueprint, render_template
famez = Blueprint('famez', __name__, url_prefix='/fa')
@famez.route('/', methods=['GET'])
def show_fa():
	return render_template('famez.html')

meim/run/core/controllers/general.py
#!/usr/bin/env python3

from flask import Blueprint, render_template, flash

controller = Blueprint('general', __name__, url_prefix='')

@controller.route('/', methods=['GET'])
def show_frontpage():
        return render_template('index.html')

meim/run/core/templates/all_listed.html
{% extends "layout.html" %}
{% block content %}
{{super()}}
 <br>  <a href="{{ url_for('s_g_smez.show_s_g_s') }}">  s g s</a>

 <br>  <a href="{{ url_for('deletemez.show_delete') }}">  delete</a>

 <br>  <a href="{{ url_for('notmez.show_not') }}">  not</a>

 <br>  <a href="{{ url_for('meowmez.show_meow') }}">  meow</a>

 <br>  <a href="{{ url_for('requestsmez.show_requests') }}">  requests</a>

 <br>  <a href="{{ url_for('ormez.show_or') }}">  or</a>

 <br>  <a href="{{ url_for('headermez.show_header') }}">  header</a>

 <br>  <a href="{{ url_for('inmez.show_in') }}">  in</a>

 <br>  <a href="{{ url_for('stringsmez.show_strings') }}">  strings</a>

 <br>  <a href="{{ url_for('raisemez.show_raise') }}">  raise</a>

 <br>  <a href="{{ url_for('REQUESTSmez.show_REQUESTS') }}">  REQUESTS</a>

 <br>  <a href="{{ url_for('if_sdfsdfmez.show_if_sdfsdf') }}">  if-sdfsdf</a>

 <br>  <a href="{{ url_for('whilemez.show_while') }}">  while</a>

 <br>  <a href="{{ url_for('printmez.show_print') }}">  print</a>

 <br>  <a href="{{ url_for('exceptmez.show_except') }}">  except</a>

 <br>  <a href="{{ url_for('famez.show_fa') }}">  fa</a>

 <br>  <a href="{{ url_for('lambdamez.show_lambda') }}">  lambda</a>

 <br>  <a href="{{ url_for('not_headermez.show_not_header') }}">  not_header</a>

 <br>  <a href="{{ url_for('meme_ssmez.show_meme_ss') }}">  meme-ss</a>

 <br>  <a href="{{ url_for('finallymez.show_finally') }}">  finally</a>

 <br>  <a href="{{ url_for('else_statementmez.show_else_statement') }}">  else statement</a>

 <br>  <a href="{{ url_for('ad_hocmez.show_ad_hoc') }}">  ad hoc</a>

 <br>  <a href="{{ url_for('listmez.show_list') }}">  list</a>

 <br>  <a href="{{ url_for('classmez.show_class') }}">  class</a>

 <br>  <a href="{{ url_for('del_fdsdfdsfmez.show_del_fdsdfdsf') }}">  del fdsdfdsf</a>

 <br>  <a href="{{ url_for('passmez.show_pass') }}">  pass</a>

 <br>  <a href="{{ url_for('return_omez.show_return_o') }}">  return-o</a>

 <br>  <a href="{{ url_for('__init__mez.show___init__') }}">  __init__</a>

 <br>  <a href="{{ url_for('breakmez.show_break') }}">  break</a>

 <br>  <a href="{{ url_for('frommez.show_from') }}">  from</a>

 <br>  <a href="{{ url_for('ismez.show_is') }}">  is</a>

 <br>  <a href="{{ url_for('sdfsdf_mez.show_sdfsdf_') }}">  sdfsdf-</a>

 <br>  <a href="{{ url_for('execmez.show_exec') }}">  exec</a>

 <br>  <a href="{{ url_for('asmez.show_as') }}">  as</a>

 <br>  <a href="{{ url_for('trymez.show_try') }}">  try</a>

 <br>  <a href="{{ url_for('returnmez.show_return') }}">  return</a>

 <br>  <a href="{{ url_for('continuemez.show_continue') }}">  continue</a>

 <br>  <a href="{{ url_for('andmez.show_and') }}">  and</a>

 <br>  <a href="{{ url_for('flask_loginmez.show_flask_login') }}">  flask_login</a>

 <br>  <a href="{{ url_for('elif_ssssmez.show_elif_ssss') }}">  elif ssss</a>

 <br>  <a href="{{ url_for('withmez.show_with') }}">  with</a>

 <br>  <a href="{{ url_for('globalmez.show_global') }}">  global</a>

 <br>  <a href="{{ url_for('importmez.show_import') }}">  import</a>

 <br>  <a href="{{ url_for('requestmez.show_request') }}">  request</a>

 <br>  <a href="{{ url_for('yieldmez.show_yield') }}">  yield</a>

 <br>  <a href="{{ url_for('Flaskmez.show_Flask') }}">  Flask</a>

 <br>  <a href="{{ url_for('assertmez.show_assert') }}">  assert</a>

 <br>  <a href="{{ url_for('formez.show_for') }}">  for</a>

 <br>  <a href="{{ url_for('defmez.show_def') }}">  def</a>
{{message2}}
{% endblock %}

meim/run/core/templates/assertmez.html
{% extends "layout.html" %}
{% block content %}
{{super()}}
<b>assert</b>
{{message2}}
{% endblock %}

meim/run/core/templates/breakmez.html
{% extends "layout.html" %}
{% block content %}
{{super()}}
<b>break</b>
{{message2}}
{% endblock %}

meim/run/core/templates/continuemez.html
{% extends "layout.html" %}
{% block content %}
{{super()}}
<b>continue</b>
{{message2}}
{% endblock %}

meim/run/core/templates/deletemez.html
{% extends "layout.html" %}
{% block content %}
{{super()}}
<b>delete</b>
{{message2}}
{% endblock %}

meim/run/core/templates/finallymez.html
{% extends "layout.html" %}
{% block content %}
{{super()}}
<b>finally</b>
{{message2}}
{% endblock %}

meim/run/core/templates/flask_loginmez.html
{% extends "layout.html" %}
{% block content %}
{{super()}}
<b>flask_login</b>
{{message2}}
{% endblock %}

meim/run/core/templates/lambdamez.html
{% extends "layout.html" %}
{% block content %}
{{super()}}
<b>lambda</b>
{{message2}}
{% endblock %}

meim/run/core/templates/layout.html
{% extends "original.html" %}

{% block content %}
{{super()}}

  {% with messages = get_flashed_messages() %}
    {% if messages %}

      {% for message in messages %}
      <br>
        <b>{{ message }}</b><br>
      {% endfor %}

    {% endif %}
  {% endwith %}
  <br>

{% endblock %}

meim/run/core/templates/login.html
{% extends "layout.html" %}
{% block content %}
{{super()}}
<h2> Login! </h2>

{{message2}}

<br>
<form action="/login/" method="post">
  <b>Username: </b>
  <input name="idask" placeholder="Username" type="text"> <br>
<br>
  <b>Password: </b>
  <input name="passwordz" placeholder="Password" type="password"> <br>

<br>
  <input type="submit">
    </form>

<br><br>
<a href="{{ url_for('general.show_frontpage') }}">Or go back to main page.</a>
<br>

{% endblock %}

meim/run/core/templates/meowmez.html
{% extends "layout.html" %}
{% block content %}
{{super()}}
<b>meow</b>
{{message2}}
{% endblock %}

meim/run/core/templates/notmez.html
{% extends "layout.html" %}
{% block content %}
{{super()}}
<b>not</b>
{{message2}}
{% endblock %}

meim/run/core/templates/original.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Wassup</title>

    <!-- Bootstrap core CSS -->
    <link href="../static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="../static/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="../static/css/simple-sidebar.css" rel="stylesheet">

</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Wassup
                    </a>
                </li>
                <li>
                    <a href="{{ url_for('general.show_frontpage') }}">Home</a>
                </li>
                <li>
                    <a href="{{ url_for('all_listedmez.show_all_listed') }}">List All</a>
                </li>
                <li>
                    <a href="{{ url_for('login.show_login') }}">Login</a>
                </li>
                <li>
                    <a href="#">Members only</a>
                </li>

            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">

              {% block content %}
                <h1>Me App</h1>
<br>
                <a href="#menu-toggle" class="btn btn-secondary" id="menu-toggle">Click to Toggle Menu</a>
<br>

                {% endblock %}

            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Bootstrap core JavaScript -->
    <script src="https://blackrockdigital.github.io/startbootstrap-simple-sidebar/vendor/jquery/jquery.min.js"></script>
    <script src="https://blackrockdigital.github.io/startbootstrap-simple-sidebar/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>

</html>

meim/run/core/templates/requestsmez.html
{% extends "layout.html" %}
{% block content %}
{{super()}}
<b>requests</b>
{{message2}}
{% endblock %}